### ISSUE TITLE
A CI tool setup

### ISSUE THREAD

**Issue by juanarbol** [tsvetomir/xlf-translate#8]
Do you think a CI system should be provided as tool for manage pull requests?

**Comment by tsvetomir** [comment]
There's a Travis CI build that will also publish the package using [semantic-release](https://github.com/semantic-release/semantic-release).

Maybe I need to catch up on the Contribution Guide though.
Do you have anything specific in mind?

**Comment by juanarbol** [comment]
No, I do not, haha, but, sure, we need to standard every contribution
